- hosts: all
  tasks:

      # We can't add repositories using the ansible apt_* commands without
      # pycurl. Note, we only want to update the cache once (in the first apt
      # command)
      # Note that we don't actually use the apt_* commands in this playbook,
      # though!
      - apt: pkg=python-pycurl state=latest update_cache=yes

      # Additional python packages
      - name: python packages
        apt: pkg={{ item }} state=latest
        with_items:
            - python-beautifulsoup
            # - python-bibtex
            # - python-biopython
            # - python-dev
            # - python-docutils
            # - python-egenix-mxproxy
            # - python-egenix-mxstack
            # - python-egenix-mxtexttools
            # - python-gadfly
            # - python-gd
            # - python-gdata
            # - python-genetic
            # - python-geoip
            # - python-gpgme
            # - python-htmlgen
            # - python-htmltmpl
            # - python-kjbuckets
            # - cython
            - python-lxml
            - python-matplotlib
            # - python-mvpa
            # - python-mvpa-lib
            # - python-mysqldb
            - python-numpy
            # - python-openpyxl
            - python-pandas
            # - python-rpy
            - python-scipy
            - python-sqlalchemy
            - python-sqlite
            - python-tornado
            - python-virtualenv
            # - python-xlrd
            # - python-xlwt
            # - python-xmpp
            - python-zmq
            - python-pytest

      - pip: name=ipython version=1.1
      - pip: name=vincent

      # It might be nice to install a newer version of requests as well,
      # installed packages cloud-init and ssh-import-id depend on it, but I
      # guess once I'm init'd, these can be removed?

      - name: Useful packages for data science and computation
        apt: pkg={{ item }} state=latest
        with_items:
            # This should automatically set up openBLAS for runtime stuff...
            - libopenblas-base
            - git

